@startuml
Користувач-->Меню_користувача: Вибір елемента меню
Меню_користувача-->Сторінка_вводу_даних: Виклик сторінки
Сторінка_вводу_даних-->БД: Збереження даних
БД-->Користувач: Дані збережено
Користувач-->Меню_користувача: Вибір елемента меню
Меню_користувача-->БД:Запит пошуку даних про студента
БД-->Модуль_обробки_запиту: Виконання пошуку
Модуль_обробки_запиту-->Користувач: Отримання списку шуканих об'єктів
@enduml